version: '3'
services:
  node:
    image: node:14
    container_name: node
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: >
      bash -c 'npm install &&
      npm run build &&
      npm run start'
    ports:
      - 3001:3000
    environment:
      - HOST=0.0.0.0
